url: "https://lesmysteresdebourges.fr" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: Les mystères de Bourges, Escape game urbain # the name of your site, e.g. ACME Corp.
sass:
  sass_dir: assets/css
include:
  - _pages
